/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Pet, PetController, PetStatusEnum, StatusEnum } from '../src';
import { testClient } from './testClient.js';
import {
  expectHeadersToMatch,
  expectMatchingWithOptions,
  makeApiCall,
} from './testHelper.js';

describe('PetController', () => {
  let controller : PetController;

  beforeAll(() => {
    controller = new PetController(testClient);
  });

  it('should Test findPetsByStatus', async () => {
    const status = StatusEnum.Available;

    const response = await makeApiCall(
      () => controller.findPetsByStatus(status)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: Pet[] = [
      {
        name: 'doggie',
        photoUrls: [
          'photoUrls5',
          'photoUrls6'
        ],
        id: BigInt(10),
        category: {
          id: BigInt(232),
          name: 'name2',
        },
        tags: [
          {
            id: BigInt(26),
            name: 'name0',
          }
        ],
        petStatus: PetStatusEnum.Sold,
      },
      {
        name: 'kitty',
        photoUrls: [
          'photoUrls7',
          'photoUrls8'
        ],
        id: BigInt(11),
        category: {
          id: BigInt(233),
          name: 'name3',
        },
        tags: [
          {
            id: BigInt(27),
            name: 'name1',
          }
        ],
        petStatus: PetStatusEnum.Available,
      }
    ];

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });

  it('should Test findPetsByTags', async () => {
    const response = await makeApiCall(
      () => controller.findPetsByTags(undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: Pet[] = [
      {
        name: 'doggie',
        photoUrls: [
          'photoUrls5',
          'photoUrls6'
        ],
        id: BigInt(10),
        category: {
          id: BigInt(232),
          name: 'name2',
        },
        tags: [
          {
            id: BigInt(26),
            name: 'name0',
          }
        ],
        petStatus: PetStatusEnum.Sold,
      },
      {
        name: 'kitty',
        photoUrls: [
          'photoUrls7',
          'photoUrls8'
        ],
        id: BigInt(11),
        category: {
          id: BigInt(233),
          name: 'name3',
        },
        tags: [
          {
            id: BigInt(27),
            name: 'name1',
          }
        ],
        petStatus: PetStatusEnum.Available,
      }
    ];

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });
});
