/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Address, addressSchema } from './address.js';

export interface Customer {
  id?: bigint;
  username?: string;
  address?: Address[];
}

export const customerSchema: Schema<Customer> = lazy(() =>
  object({
    id: ['id', optional(bigint())],
    username: ['username', optional(string())],
    address: ['address', optional(array(addressSchema))],
  })
);
