/**
 * Swagger Petstore - OpenAPI 3.0Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { Category, categorySchema } from './category.js';
import { PetStatusEnum, petStatusEnumSchema } from './petStatusEnum.js';
import { Tag, tagSchema } from './tag.js';

export interface Pet {
  name: string;
  photoUrls: string[];
  id?: bigint;
  category?: Category;
  tags?: Tag[];
  /** pet status in the store */
  petStatus?: PetStatusEnum;
}

export const petSchema: Schema<Pet> = lazy(() =>
  object({
    name: ['name', string()],
    photoUrls: ['photoUrls', array(string())],
    id: ['id', optional(bigint())],
    category: ['category', optional(categorySchema)],
    tags: ['tags', optional(array(tagSchema))],
    petStatus: ['petStatus', optional(petStatusEnumSchema)],
  })
);
